org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.java.home=C:/Program Files/Zulu/zulu-25

minecraft_version=26.1.2
yarn_mappings=mojang-official
loader_version=0.19.3
loom_version=1.15.5
java_version=25
fabric_version=0.153.0+26.1.2
fabric_api_base_version=2.0.3+ece063234c
fabric_command_api_v2_version=3.0.5+e2bdee784c
fabric_creative_tab_api_v1_version=5.0.11+d871b99e4c
fabric_entity_events_v1_version=5.0.2+e2bdee784c
fabric_events_interaction_v0_version=5.2.2+07b380be4c
fabric_lifecycle_events_v1_version=4.1.1+df84eb3d4c
fabric_networking_api_v1_version=6.3.1+554860db4c
fabric_object_builder_api_v1_version=23.0.17+b95dd56e4c
fabric_rendering_v1_version=23.2.0+c9da2e974c

mod_version=1.1.2
maven_group=cn.quit5700
archives_base_name=quick-build
