org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.java.home=C:/Program Files/Java/jdk-21

minecraft_version=1.21.8
yarn_mappings=mojang-official
loader_version=0.17.3
loom_version=1.11.8
java_version=21
fabric_version=0.136.1+1.21.8
jade_file_id=6906804
fabric_api_base_version=2.0.4+ece063239e
fabric_command_api_v2_version=3.1.0+00cb03469e
fabric_creative_tab_api_v1_version=5.0.14+d871b99e9e
fabric_entity_events_v1_version=5.0.5+06488ac19e
fabric_events_interaction_v0_version=5.2.2+07b380be4c
fabric_lifecycle_events_v1_version=4.1.3+4575b05f9e
fabric_networking_api_v1_version=6.3.3+72073ef09e
fabric_object_builder_api_v1_version=24.0.6+46a6d00c9e
fabric_rendering_v1_version=25.2.0+2b0d8a229e

mod_version=1.0.0
maven_group=cn.quit5700
archives_base_name=quick-build
